apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: app1-
namespace: app1

resources:
- ../../../base/nginx/

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: ingress-nginx
    patch: |- 
      - op: replace
        path: /spec/values/controller/resources
        value: 
          requets:
            cpu: 200m
            memory: 300Mi
