apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n1-c3
  namespace: flux-system
spec:
  interval: 30s
  path: ./fluxcd/clients/client-3/app1/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n2-c3
  namespace: flux-system
spec:
  interval: 30s
  path: ./fluxcd/clients/client-3/app2/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
