apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: client-2-

resources:
- ../base/

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: guestbook
    path: ./application.yaml
