apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: app1c1-
namespace: app1

resources:
- ../../../base/nginx/

patches:
  - target:
      version: v1
      kind: Deployment
      name: nginx-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
