apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiki

resources:
- ../../../base/podinfo/

# patches:
  # - target:
  #     group: helm.toolkit.fluxcd.io
  #     version: v2beta1
  #     kind: HelmRelease
  #     name: wiki
  #   patch: |-
  #     - op: replace
  #       path: /spec/values
  #       value:
  #         replicaCount: 2
