apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: app2-
namespace: app2

resources:
- ../../../base/nginx/

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: ingress-nginx
    patch: |- 
      - op: replace
        path: /spec/replicas
        value: 4
