apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: app2-
namespace: app2

resources:
- ../../../base/nginx/

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
      spec:
        replicas: 4 # tells deployment to run 2 pods matching the template
