apiVersion: v1
kind: Namespace
metadata:
  name: wiki
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: requarks
  namespace: wiki
spec:
  interval: 5m0s
  url: https://charts.js.wiki
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki
  namespace: wiki
spec:
  interval: 30s
  chart:
    spec:
      chart: wiki
      version: 2.2.20
      sourceRef:
        kind: HelmRepository
        name: requarks
        namespace: wiki
      interval: 30s
  values:
    replicacount: 1
